### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wifasoi** [wifasoi/WaveDromTikZ#2]
Hi,
sorry to bother you, but i would like to use your script in the sphinx-wavedrom (Shh... quiet... the sphinx-wavedrom developer doesn't know :P) project (as a dependency, for rendering wavedrom snippets in the pdf output).
Long story short, the repo is missing the license, so i cant use it :(
Can you specify witch one you want to use? (by adding the LICENSE file in the root of the repo, or leave it without license if you don't want to license your code to anyone)
Thanks for your consideration.

**Comment by mossblaser** [comment]
Thanks for bringing that up! I've added an MIT license which I hope will be suitable.

As you can probably tell, this project has been unmaintained for a long time, would you be interested in taking over since it seems like you're about to become its main and only user?

**Comment by wifasoi** [comment]
So, the missing license was a bait... and I took a big bite :P
I can try to take care of your child(the project), if you want.

**Comment by mossblaser** [comment]
Hah! Yes, I'll take this generous interpretation ;).

Of course there would be no hard feelings from me if you too chose to abandon it too! Best of luck :)
